server:
  port: 8008
spring:
  application:
    name: gateway-demo

  cloud:
    nacos:
      discovery:
        server-addr: 10.228.131.21:8848
        enabled: true
        cluster-name: SH

    gateway:
      discovery:
        locator:
          enabled: true  #默认为false,设为true则可以通过微服务名访问服务
      enabled: true  #是否开启网关
      routes:
      - id: nacos-client
        uri: lb://nacos-client
        predicates:
        - Path=/hiS*
      - id: nacos-provider
        uri: http://localhost:8001 #lb://nacos-provider
        predicates:
        - Path=/h*

#      - id: nacos-provider-8001
#        uri: lb://nacos-provider
#        predicates:
#        - Weight=group1, 8
#        - Path= /*
#      - id: nacos-provider-8002
#        uri: lb://nacos-provider
#        predicates:
#        - Weight=group1, 2
#        - Path= /*



